### ISSUE TITLE
Compatibility LiipImagine filters

### ISSUE THREAD

**Issue by qvasdoria** [BitBagCommerce/SyliusCmsPlugin#281]
I'm trying to add a **LiipImagine filter** to a media image

```twig
<div style="background-image: url({{ image.path|imagine_filter('sylius_small') }});">
```

However, BitBag seems to add `/media/image/` as prefix to the image URL, while Sylius doesn't; which make the resolve path invalid.

Is BitBagCMS compatible with LiipImagine image size filters ?

**Comment by decemvre** [comment]
@qvasdoria I am having the same issue. Did you find a solution to this?

**Comment by decemvre** [comment]
@qvasdoria you can change or remove the media/image/ but the bitbag code still appends a / in the code. It's hardcoded. Which then either creates a folder with no name // or fails.

In my AWS S3 it creates a folder with no name.

**Comment by decemvre** [comment]
@qvasdoria I believe I solved your issue. You just need to override the bitbag cms services with your own in your own project, and then the configuration files and remove the hardcoded / if you're uploading to AWS S3 with knp_gaufrette and while overriding the config files you can remove or change /media/image as well.

I'll try to solve the LiipImagine filter as well or just not use it myself but I imagine the solution is similar.

**Comment by aaroncunliffe** [comment]
@decemvre would it be possible for you to share how you had solved this issue? What services need to be overwritten and changed?

I have stumbled across this open issue and it is the exact problem I am trying to solve, I have managed to alter the knp_gaufrette configuration to get uploads working correctly, but I have been unable to fix retrieval.

**Comment by decemvre** [comment]
![image](https://user-images.githubusercontent.com/3599668/82177063-28ee7080-98e1-11ea-8e67-3bc4a188d6b0.png)

The code is in a private repo and I can't share it however these are the services you need to override; simply create these files in your project and then override the exact service names in a configuration file in packages.

1. In UploadEditorImageAction I passed it the aws s3 region and bucket in the constructor using the service dependency injection configuration and the in the JsonResponse I appended those values before $media->getPath()
This will make the WYSIWYG Editor in the CMS load the preview after you've uploaded the file in the Admin panel

2. In MediaUploader remove the hardcoded '/' in the call to $media->setPath('/' . $path)
That will prevent folders with empty names being created in the aws bucket.

3. And finally in GenericProvider pass it the aws s3 region and bucket again in the constructor and then modify the render method and add a new property to the $media object on the fly like $media->s3Path = .. (I did this because I didn't want to override the Entity too) where  you append the those values before the $media->getPath.
Don't use $media->setPath() as that will on occasion also save the path to the database and you don't want that.
Finally override the image.html.twig template that the bundle uses and change .path to src="{{ media.s3Path }}"


Obviously this is a bit of a hack fix but because there are hardcoded bits of code in the bundle already clearly it's not designed to upload to aws S3 in this version; so this worked for me until the next version comes around.

**Comment by cirykpopeye** [comment]
I simply "fixed" it this way:

```
liip_imagine:
    loaders:
        default:
            filesystem:
                data_root:
                    - "%kernel.project_dir%/public"
```

It specifies where the filesystem is so liip knows where to start loading images.

**Comment by mitas** [comment]
It works, thank you !

**Comment by mitas** [comment]
> I simply "fixed" it this way:
> 
> ```
> liip_imagine:
>     loaders:
>         default:
>             filesystem:
>                 data_root:
>                     - "%kernel.project_dir%/public"
> ```
> 
> It specifies where the filesystem is so liip knows where to start loading images.

It works, thank you !

**Comment by leszczuu** [comment]
fixed with 3.0.0 release

**Comment by t-n-y** [comment]
> My final problem is that the WYSIWYG editor in the admin panel doesn't link to images in AWS S3.

Hi, did you find a solution ? i have the exact same problem

**Comment by decemvre** [comment]
> > My final problem is that the WYSIWYG editor in the admin panel doesn't link to images in AWS S3.
> 
> Hi, did you find a solution ? i have the exact same problem

I honestly don't remember if I fixed it or just left it as a known bug; the project went bust after a few months.
