### ISSUE TITLE
Failed to copy "/srv/sylius/vendor/babdev/pagerfanta-bundle/Resources/public/css/pagerfantaDefault.css" because file does not exist.

### ISSUE THREAD

**Issue by fabianobonomini** [BitBagCommerce/SyliusCmsPlugin#408]
I am using  sylius 1.10.5

I followed you readme until last step

`
bin/console sylius:theme:assets:install --symlink
`

that return me an error

`
Failed to copy "/srv/sylius/vendor/babdev/pagerfanta-bundle/Resources/public/css/pagerfantaDefault.css" because file does not exist.
`

Any idea why it is happening?

Plus the labels inside the admin are not translated in italian. I dont know if it's normal or not.

Thanks
Fabiano

**Comment by fabianobonomini** [comment]
I tried to install the package `requires babdev/pagerfanta-bundle`

with the command 
`
COMPOSER_MEMORY_LIMIT=-1 composer require babdev/pagerfanta-bundle

`

but no luck

`
Problem 1
    - sylius/sylius v1.10.5 requires babdev/pagerfanta-bundle ^2.5 -> satisfiable by babdev/pagerfanta-bundle[2.x-dev, v2.10.0, v2.10.1, v2.11.0, v2.5.0, v2.5.1, v2.5.2, v2.6.0, v2.6.1, v2.7.0, v2.8.0, v2.9.0] but these conflict with your requirements or minimum-stability.
    - sylius/sylius v1.10.5 requires babdev/pagerfanta-bundle ^2.5 -> satisfiable by babdev/pagerfanta-bundle[2.x-dev, v2.10.0, v2.10.1, v2.11.0, v2.5.0, v2.5.1, v2.5.2, v2.6.0, v2.6.1, v2.7.0, v2.8.0, v2.9.0] but these conflict with your requirements or minimum-stability.
    - sylius/sylius v1.10.5 requires babdev/pagerfanta-bundle ^2.5 -> satisfiable by babdev/pagerfanta-bundle[2.x-dev, v2.10.0, v2.10.1, v2.11.0, v2.5.0, v2.5.1, v2.5.2, v2.6.0, v2.6.1, v2.7.0, v2.8.0, v2.9.0] but these conflict with your requirements or minimum-stability.
    - Installation request for sylius/sylius (locked at v1.10.5, required as ~1.10.0) -> satisfiable by sylius/sylius[v1.10.5].

`

**Comment by jakubtobiasz** [comment]
I've performed an investigation and I've found what causes this error.

In `Sylius\Bundle\ThemeBundle\Asset\Installer\AssetsInstaller` at line 123 is method `installAsset` taking two parameters `$origin`, `$target` and `$symlinkMask`.

While executing `bin/console sylius:theme:assets:install --symlink` this method for PagerfantaBundle is executed twice.

First execution:
`$origin` -> `/Users/jakubtobiasz/PhpstormProjects/clean-sylius-2/vendor/babdev/pagerfanta-bundle/Resources/public/css`
`$target` -> `public/bundles/babdevpagerfanta/css`

Second execution:
`$origin` -> `/Users/jakubtobiasz/PhpstormProjects/clean-sylius-2/vendor/babdev/pagerfanta-bundle/Resources/public/css/pagerfantaDefault.css`
`$target` -> `public/bundles/babdevpagerfanta/css/pagerfantaDefault.css`

As you can notice the second execution tries to create symlink `pagerfantaDefault.css` inside `public/bundles/babdevpagerfanta/css` directory which is symlink to to `/Users/jakubtobiasz/PhpstormProjects/clean-sylius-2/vendor/babdev/pagerfanta-bundle/Resources/public/css` in my case. The result is circular symlink:
![image](https://user-images.githubusercontent.com/80641364/146042676-e9e1c96f-601c-4805-9651-59fe89c20191.png)

Temporary solution is to remove `vendor` or at least `vendor/babdev` directory and run `composer install`. It will download the fresh package with the "real" `pagerfantaDefault.css` file. Symlink in `public` directory still points to the right location so it works.

This bug is more related to the Sylius itself rather than this concrete plugin. I've tested it out with and without CMS plugin and the same result.

**Comment by fabianobonomini** [comment]
thanks @jakubtobiasz, very kind of you.

I "solved", removing the vendor folder

**Comment by elboletaire** [comment]
Following the installation instructions, when running 

~~~bash
bin/console sylius:theme:assets:install --symlink 
~~~

The command tries to create an aliased file of the css file itself (pointing to itself, thus causing the error). Contents of `vendor/babdev/pagerfanta-bundle/Resources/public/css` before running the command:

![imatge](https://user-images.githubusercontent.com/153305/193550097-a75ef287-558d-4fa0-b381-9ca87116169e.png)

Error and contents after running the specified command:
![imatge](https://user-images.githubusercontent.com/153305/193550219-09789e91-6cf6-4bc3-9648-db07e6d16099.png)
