### ISSUE TITLE
CKEditor insert media image plugin not working because variable `route` is not defined

### ISSUE THREAD

**Issue by gigamarr** [BitBagCommerce/SyliusCmsPlugin#419]
`./vendor/bitbag/cms-plugin/src/Resources/public/js/ckeditor-plugins/dialogs/index.js` line 127 function `showMediaImage`

variable `route` is never defined. I want to patch it but I'm not sure what the value of `route` is supposed to be

**Comment by Harvel218** [comment]
Hi, thank you for your efford!, in order to make it work you need to pass route from "backend" to handle it via cms plugin javascripts - in plugin (test/application) we did it like this: 
in tests/Application/templates/bundles/SyliusAdminBundle/Layout/_scripts.html.twig
<script>
    const route = "{{ path('bitbag_sylius_cms_plugin_admin_ajax_media_by_name_phrase')|escape('js') }}";
</script>

You can pass/declare this variable where you want, but it have to be achievable by cms plugin pages (in _scripts it should be fine)
