### ISSUE TITLE
Missing changelog and update information on v1.1.0

### ISSUE THREAD

**Issue by Amunak** [BitBagCommerce/SyliusCmsPlugin#99]
I've updated a project with composer and noticed that you made a new release. There is however no information about it - nothing in release description or title, nothing in readme, your repository has no changelog or upgrading info.

Which would probably be okay if you didn't include some 300 commits in the release and managed to change names of all tables, thus basically creating a BC break as the default Symfony Schema Update tool doesn't see it as a rename and drops and re-creates the tables instead, potentially resulting in data loss if it goes unnoticed.

Please create and maintain a changelog and upgrade info (just like Sylius does) and if you make a big schema change providing an example migration would be nice too.

**Comment by bitbager** [comment]
Yes, we will definitely need to manage it and I have it in my backlog. Sorry for all BCs, hope you will manage to upgrade your instance without regression. 

Before we'll tag v1.1.1, we will create a changelog file. There will be a few more BCs due to plugin standards that were recently announced by Sylius.

@shinoks, could you please take a look at it? 🙂

**Comment by shinoks** [comment]
@bitbager  Ok, I have added changelog to PR

**Comment by bitbager** [comment]
Thanks! @Amunak, we will try to prepare an UPGRADE.md file, stay tuned. For now, you can generate the migrations, write a simple SQL that moves the data to new tables and drops the old tables once it's done. That's a proven workflow we applied recently in our project which is using this plugin.
